spring:
  application:
    name: insurance-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: insurance-eureka
  client:
    # Al ser el propio servidor, no se registra ni busca en sí mismo
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
